repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

-   repo: local
    hooks:
    - id: generate-content-pages
      name: generate-content-pages
      entry: bash -c 'notes generate-readme-files'
      language: system
      pass_filenames: false
